### ISSUE TITLE
[bug] <a id="someting"></a> visible in rendering

### ISSUE THREAD

**Issue by aurelienvlg** [icewind1991/files_markdown#100]
Hello Robin, 

![nextcloud-markdown-bug](https://user-images.githubusercontent.com/26377719/42413995-7bae30f8-822c-11e8-9a63-1e9b7bc77940.png)

As we can see in the screenshot, the inline html is not rendered correctly.

Regards.

**Comment by Schmuuu** [comment]
Hi, 
This is reported already. HTML, in general, is not working for a long time already:
https://github.com/icewind1991/files_markdown/issues/72

**Comment by icewind1991** [comment]
closing as duplicate of #72
