### ISSUE TITLE
enumeration indentation using tab key

### ISSUE THREAD

**Issue by Miroka96** [icewind1991/files_markdown#105]
Hello,

like in some other online note apps, I would like to be able to indent a whole line starting with "[ ]*\* " (so just an enumeration at nth level) by just pressing the tabulator key. The inverse direction is already possible using shift+tab.

Or did I just miss this feature?

BR,
Miroka96

**Comment by Miroka96** [comment]
By now I only found the temporary solution to highlight at least one character in a line and then I can use the tab key to indent the whole line.

It would still be nice, if the indentation is happening when pressing the tab key at the beginning of the text of a line.

**Comment by icewind1991** [comment]
Issues with text editing should be reported in the [texteditor repo](https://github.com/nextcloud/files_texteditor).
