### ISSUE TITLE
How to show latex formula pretty?

### ISSUE THREAD

**Issue by seahome45** [icewind1991/files_markdown#112]
This is great work ! But I got latex math formula shown in html not as beautiful as the one shown in the README.md. Check the following two pictures. Do I miss something to install with nextcloud ?  

**math in README**
![LaTeX math](https://raw.githubusercontent.com/icewind1991/files_markdown/master/screenshots/math.png)

**math in my nextcloud**
![](https://i.imgur.com/uwNU6mm.png)

**Comment by st3iny** [comment]
I have the same problem on my nextcloud installation. Is there any fix available?

**Comment by thstyl2000** [comment]
It is font-related, see #168 .
