### ISSUE TITLE
After update to 2.0.6 - Mixed and Preview modes no longer working

### ISSUE THREAD

**Issue by mcuix** [icewind1991/files_markdown#123]
After updating the Markdown editor in Nextcloud to version 2.0.6, the Mixed and Preview modes only show blank. Same for old md and new md files.

**Comment by mcuix** [comment]
Degraded Markdown Editor back to version 2.0.6. Editor now working again.

**Comment by icewind1991** [comment]
Can you try clearing the browser cache and see if that helps?

**Comment by mcuix** [comment]
I tried clearing the browser cache. Uninstalled it, reinstalled it. Rebooted the server. I even tried a manual re-install. Didn’t help. I ended up restoring a backup of the previous version, and everything seems to be working fine.

**Comment by Aecroo** [comment]
after the update i had the same issue with google chrome. deleting the browser cache worked for me.

**Comment by mcuix** [comment]
I’m using Firefox and Chrome. Same problem on both. For now I’ll stick to the older version.

**Comment by mcuix** [comment]
I reinstalled Firefox and Chrome. Now its working.
