### ISSUE TITLE
Editing converts line endings to CR LF

### ISSUE THREAD

**Issue by wolframroesler** [icewind1991/files_markdown#125]
Editing a .md file in the markdown editor automatically converts all line ending to Windows style (CR LF), even if the file is using Unix-style (LF only) line endings. Instead, the editor should analyze the file to find out which style it's using, create new lines with that style, and leave everything else unchanged.

To understand why the present behaviour is a problem, put a big Unix-style .md file into a git repo, put the repo into your Nextcloud, edit the file with the markdown editor, and then do "git diff".

**Comment by tessus** [comment]
Yea, I have deactivated this app for now, because it ruins my markdown files.

I'm not sure if the repo owner reads any problem reports. My other issue hasn't received any reply yet either.

**Comment by wolframroesler** [comment]
Too bad. Let's see when I get around to learning TypeScript so I can fix it myself, since this is a real showstopper.

**Comment by icewind1991** [comment]
Issues with the editor itself should be submitted to the  `files_texteditor` repo, this app only deals with the markdown preview

**Comment by wolframroesler** [comment]
Thanks for the info, and sorry for bothering you here.

Reported it here: https://github.com/nextcloud/files_texteditor/issues/156
