### ISSUE TITLE
Nextcloud 17 support

### ISSUE THREAD

**Issue by nougad** [icewind1991/files_markdown#132]
Nextcloud 17 rc1 is released: https://nextcloud.com/blog/nextcloud-17-scales-up-and-improves-data-protection-with-remote-wipe-collaborative-text-editor-2fa-updates-ibm-spectrum-scale-support-and-global-scale-improvements/

It would be great if the app is supported on release date :)

**Comment by icewind1991** [comment]
2.1.0 is released with nc17 support
