### ISSUE TITLE
Dont work after update nextcloud 17

### ISSUE THREAD

**Issue by letopisec3** [icewind1991/files_markdown#135]
After updating to nextcloud 17, markdown stopped working. App text opens instead of makdown. Disabling app text does offer to download instead of editing

**Comment by adsduarte** [comment]
Hi,
I'm having the same issue here. Does anyone know how to chose the default app for markdown files?
Tks

**Comment by squintarelli** [comment]
the file created with the "+" command has a "," (comma) in the filename instead of a "." (period)

**Comment by Schmuuu** [comment]
Hello everybody,

I just discovered the same issue and found out that on my system the app "Plain text editor" was missing after the update to NC17. This "Plain text editor" (name 'files_texteditor' in the apps folder on filesystem) is the basis for the files_markdown app.

Could you guys please check if have the same problem with the missing base app? In that case we should open an issue in the other repository.

Just in case you see the exact same issue, here is how you can solve it with SSH access:
```
cd /path/to/nextcloud/apps
wget https://github.com/nextcloud/files_texteditor/archive/v17.0.0.tar.gz
tar -xzf v17.0.0.tar.gz
chmod -R <webserver user>:<webserver user> files_texteditor-17.0.0
mv files_texteditor-17.0.0 files_texteditor
find files_texteditor/ -type f -print0 | xargs -0 chmod 640
find files_texteditor/ -type d -print0 | xargs -0 chmod 750
rm v17.0.0.tar.gz
``` 

The reason I did this manually (and why I post my steps here) is, that I didn't find the app on my server as admin under "Apps" for download and also restoring that app folder from the backup and trying to update it then was not possible. So it seems these manual steps are the only way. Hope it helps.

**Comment by Schmuuu** [comment]
Hello again,

I tried to find out a bit more about this issue and it seems the plain text app got somehow removed from the app store and consequently is no longer available for updates or downloads.

I created an issue in the other repo. So in case you want to follow that issue:
https://github.com/nextcloud/files_texteditor/issues/185

**Comment by marsstark** [comment]
Hi Schmuuu, thanks for the info. I followed the steps and it worked. Now I have `Mardown Editor` working again.

**Comment by henricazottes** [comment]
I tried to follow those steps but unsuccessfully. I can see and enable the app in the ui but can't create (the option is missing from "+") nor edit files (it opens the download popup).

@Schmuuu is there anything else to do other than the steps listed ?

I'm on php 7.1, nextcloud 17, files_texteditor 2.9.0 (same one from the steps)

**Comment by Schmuuu** [comment]
Hi @henricazottes 

Maybe we should talk about your issue via PNs. Could you write me in the NC forum?
https://help.nextcloud.com/u/schmu

Please try and send the following:
- try again after clearing browser cache
- check if app "Markdown Editor" is enabled
- send a screenshot from the open "+" Menu
- a screenshot from the open "..." menu of a .txt file
- a screenshot from the open "..." menu of a .md file

**Comment by henricazottes** [comment]
Thanks for your guidelines, I managed to make it work by setting `644` and `755` permissions.

**Comment by BrookeDot** [comment]
> Could you guys please check if you have the same problem with the missing base app? In that case we should open an issue in the other repository.

It sounds like the root cause is indeed the missing plugin upstream. Has this been reported to the correct repo or should I do this? With NC 17.1 coming out in a bit I'm not sure it'll make it in time for that but maybe for 17.2 or 18 :)

**Comment by Schmuuu** [comment]
> It sounds like the root cause is indeed the missing plugin upstream. Has this been reported to the correct repo or should I do this? With NC 17.1 coming out in a bit I'm not sure it'll make it in time for that but maybe for 17.2 or 18 :)

Yes, I opened an issue for that already and it's a sad story actually:
https://github.com/nextcloud/files_texteditor/issues/185#issuecomment-546934926

You could support me in that thread however and add your concerns as well, if you want.

**Comment by clorenz150** [comment]
I restored the `files_texteditor` folder from a backup an managed to enable it (min- adn max-version is 16).

Having all three enabled (`text`, `files_texteditor` and `files_markdown`) works, but not smooth.

You can "edit with the only text editor", which opens `files_markdown`, but `text` has some caching and recognizes changes, done by other apps, only when it tries to write changes. Then you can revert to the saved version.

**Comment by jimjulian** [comment]
> Hello everybody,
> 
> I just discovered the same issue and found out that on my system the app "Plain text editor" was missing after the update to NC17. This "Plain text editor" (named 'files_texteditor' in the apps folder on filesystem) is the basis for the files_markdown app.
> 
> Could you guys please check if you have the same problem with the missing base app? In that case we should open an issue in the other repository.
> 
> Just in case you see the exact same issue, here is how you can solve it with SSH access:
> 
> ```
> cd /path/to/nextcloud/apps
> wget https://github.com/nextcloud/files_texteditor/archive/v17.0.0.tar.gz
> tar -xzf v17.0.0.tar.gz
> mv files_texteditor-17.0.0 files_texteditor
> find files_texteditor/ -type f -print0 | xargs -0 chmod 640
> find files_texteditor/ -type d -print0 | xargs -0 chmod 750
> sudo chown -R <webserver user>:<webserver user> files_texteditor
> rm v17.0.0.tar.gz
> ```
> 
> The reason I did this manually (and why I post my steps here) is, that I didn't find the app on my server as admin under "Apps" for download and also restoring that app folder from the backup and trying to update it then was not possible. So it seems these manual steps are the only way. Hope it helps.

I used the 17.0.1 file, and it worked. Thank you.

**Comment by vincowl** [comment]
@jimjulian Doesn't work here with 17.0.1 : .md files still open with Text and no option to open it with a different app. Is there a trick or something to solve this ?

**Comment by Stapper** [comment]
@vincowl Check if files_texteditor is enabled in your apss after unpacking it in the folder.

**Comment by vincowl** [comment]
@Stapper No, I don't even see a trace of files_texteditor in the apps....

**Comment by henricazottes** [comment]
Seems like it has been put back in the store: https://github.com/nextcloud/app-certificate-requests/pull/282

**Comment by yaringal** [comment]
Hi all, is there a way to have this enabled at the same time as the new collaborative text editor? (ie choose which editor to open .md files with)

**Comment by ShiboJiang** [comment]
> Hello everybody,
> 
> I just discovered the same issue and found out that on my system the app "Plain text editor" was missing after the update to NC17. This "Plain text editor" (named 'files_texteditor' in the apps folder on filesystem) is the basis for the files_markdown app.
> 
> Could you guys please check if you have the same problem with the missing base app? In that case we should open an issue in the other repository.
> 
> Just in case you see the exact same issue, here is how you can solve it with SSH access:
> 
> ```
> cd /path/to/nextcloud/apps
> wget https://github.com/nextcloud/files_texteditor/archive/v17.0.0.tar.gz
> tar -xzf v17.0.0.tar.gz
> mv files_texteditor-17.0.0 files_texteditor
> find files_texteditor/ -type f -print0 | xargs -0 chmod 640
> find files_texteditor/ -type d -print0 | xargs -0 chmod 750
> sudo chown -R <webserver user>:<webserver user> files_texteditor
> rm v17.0.0.tar.gz
> ```
> 
> The reason I did this manually (and why I post my steps here) is, that I didn't find the app on my server as admin under "Apps" for download and also restoring that app folder from the backup and trying to update it then was not possible. So it seems these manual steps are the only way. Hope it helps.

I use this way in docker - nc 17.0.1，it worked. Thanks!

**Comment by nerdeirodasilva** [comment]
(snip)
> ```
> cd /path/to/nextcloud/apps
> wget https://github.com/nextcloud/files_texteditor/archive/v17.0.0.tar.gz
> tar -xzf v17.0.0.tar.gz
> mv files_texteditor-17.0.0 files_texteditor
> find files_texteditor/ -type f -print0 | xargs -0 chmod 640
> find files_texteditor/ -type d -print0 | xargs -0 chmod 750
> sudo chown -R <webserver user>:<webserver user> files_texteditor
> rm v17.0.0.tar.gz
> ```

(snip)

Thank you, @Schmuuu , this restored sanity to my NC 18.

**Comment by VincentSC** [comment]
Had to disable and enable "text" app to make it work after I did the @Schmuuu's procedure

**Comment by e-alfred** [comment]
So many people like this Markdown editor (me as well), hopefully @rullzer can upload the files_texteditor app to the app store soon.

**Comment by ifuchs** [comment]
I have not gotten this to work regardless of which version of Plain Text Editor I use. There seem to be 3 apps that all have something to do with editing text. 1. Text, 2. Plain Text Editor, 3. Markdown Editor. No combination seems to work on NC 18. If I disable Plain Text editor I cannot open code files but I can vide/edit .md files.

**Comment by aschoerg** [comment]
I have a hosted instance of nextcloud 18 with now shell access... :cry: 

What are the plans for the future? Stall the project or implement a way around?

**Comment by ifuchs** [comment]
Well, I have had some success. I installed Plain Text Editor v2.10 and disabled Text app. I can now open and edit code files. My only problem with this is that the editor is using Ace and it is configured to add CR to each line. This is can be a problem on linux. I changed the config in Ace from "windows" to "auto" but either that doesn't work or it is not taking effect for some reason. So, the markdown editor is showing side-by-side view and code files are viewable/editable. Obviously it would be nice if this didn't require more effort than downloading and enabling in the web ui.

**Comment by ThomersZauber** [comment]
Hi,

I got the same problem, not being able to use the Markdown Editor on Nextcloud 18.0.3.
Similarly to @aschoerg, I also run Nextcloud on a hosted server without SSH access.

Anyone got an ider how to solve this problem in this situation?

Thanks!

**Comment by maenujem** [comment]
The `files_texteditor` (https://github.com/nextcloud/files_texteditor/issues/185) has been published to the App Store by @juliushaertl .

Using the following steps, the markdown-viewer/plain-text-editor now works again like a charm:
1. disable default "text"-app
2. add "plain text editor"-app
3. add "markdown editor"-app

**Comment by raneon** [comment]
> The `files_texteditor` ([nextcloud/files_texteditor#185](https://github.com/nextcloud/files_texteditor/issues/185)) has been published to the App Store by @juliushaertl .
> 
> Using the following steps, the markdown-viewer/plain-text-editor now works again like a charm (NC 18.0.3, Linux-Server):
> 
>     1. disable default "text"-app
> 
>     2. add "plain text editor"-app
> 
>     3. add "markdown editor"-app

Yes, this worked for me. And I'm glad to get rid of the default text app!

**Comment by thomas-mc-work** [comment]
It would be great to find this little tutorial in the README. Otherwise, new users will hardly find out themselves how to get it working.

**Comment by lvarnava** [comment]
Markdown Editor does not work.

NC 17.0.7
Ubuntu 18.04.4
apache 2.4.29
php 7.2.24
PostgreSQL 10.12
Plain text editor 2.11.0
Markdown Editor 2.3.0
Text disabled

**Comment by fds2610** [comment]
> > The `files_texteditor` ([nextcloud/files_texteditor#185](https://github.com/nextcloud/files_texteditor/issues/185)) has been published to the App Store by @juliushaertl .
> > Using the following steps, the markdown-viewer/plain-text-editor now works again like a charm (NC 18.0.3, Linux-Server):
> > ```
> > 1. disable default "text"-app
> > 
> > 2. add "plain text editor"-app
> > 
> > 3. add "markdown editor"-app
> > ```
> 
> Yes, this worked for me. And I'm glad to get rid of the default text app!

This does not work anymore. plain_text_editor does not install anymore. (Certificate error?).

**Comment by SnailDove** [comment]
> > > The `files_texteditor` ([nextcloud/files_texteditor#185](https://github.com/nextcloud/files_texteditor/issues/185)) has been published to the App Store by @juliushaertl .
> > > Using the following steps, the markdown-viewer/plain-text-editor now works again like a charm (NC 18.0.3, Linux-Server):
> > > ```
> > > 1. disable default "text"-app
> > > 
> > > 2. add "plain text editor"-app
> > > 
> > > 3. add "markdown editor"-app
> > > ```
> > 
> > 
> > Yes, this worked for me. And I'm glad to get rid of the default text app!
> 
> This does not work anymore. plain_text_editor does not install anymore. (Certificate error?).

 I got the same error as you
