### ISSUE TITLE
Modify How App Saves New Lines

### ISSUE THREAD

**Issue by thw26** [icewind1991/files_markdown#139]
One thing I've noticed is the way this app saves markdown files.
If I create a file outside this app and separate lines of a single paragraph with a single new line (so by markdown I am not starting a new paragraph; this file is given in Before below) but then open the file in the Nextcloud app, the app writes/saves file and removes these new line elements (this file is given in After below).

[Before](https://pastebin.com/4baqhdvE)

[After](https://pastebin.com/7yKz3RrT)

Is it possible to change the saving behavior so that it maintains the structure of Before and not After or enable an option for this?

**Comment by KyleWJohnston** [comment]
I tried to replicate this with various line ending styles and didn't have the issue. Either it's been fixed or you're actually using https://github.com/nextcloud/text, which does modify the original file.

This app will combine lines without a blank line between them for the preview (see below), but it will not change the source file.
![Markdown test](https://user-images.githubusercontent.com/7908653/118661842-1db07800-b7b5-11eb-9c20-cb499dcea05c.png)

**Comment by thw26** [comment]
Good enough for me. I likely was working with the other software. I will close.
