### ISSUE TITLE
Is this project still under active development?

### ISSUE THREAD

**Issue by fthommen** [icewind1991/files_markdown#141]
Hello,

I wonder, if this project is still under active development.  I see lots of unsolved issues back until 2014, the last comment by @icewind1991 seems to be from last autumn and the release notes for version 2.2.0 says, that is it compatible with NextCloud 18, but as issue #136 (and maybe others) shows, this is not the case.

Before the upgrade to NC18, Markdown Editor was the online MD editor of my choice and I wonder, if its better to look for an alternative solution.

No criticism, just a question :-)

**Comment by icewind1991** [comment]
Development is limited to keeping the app working on the latest nc version.

And this app *does* work with nc18 if `files_texteditor` is installed. (which, yes, currently requires manual installation from git, see also https://github.com/nextcloud/files_texteditor/pull/192)

**Comment by ifuchs** [comment]
I installed manually and cannot get it work.
