### ISSUE TITLE
Conflicts with Text app and doesn't work on Nextcloud 19.0

### ISSUE THREAD

**Issue by jgaehring** [icewind1991/files_markdown#148]
Hi, just want to report something I had a little trouble with today and solved, in case any one else encounters something similar. I had tried to install this app via the store, but when I went to load markdown files, they were not loading with files_markdown.

I had saw that the Text Editor app needed to be installed and enabled, but I thought I had it installed and enabled. My Nextcloud installation is relatively recent, and I believe it came preloaded with that app.

It was not until I read through #135 that I realized I had a _different_ text editor app, "Text" instead of "Plain text editor". I installed and enabled "Plain text editor", no dice. Only once I disabled "Text" did files_markdown start to work.

I'm not sure if there has been a change with Nextcloud 19.0 in terms of what apps it comes with already installed (maybe it's just my provider preloading them?), but I thought it was worth addressing here, in case anyone else gets confused. Happy to submit a PR to document this if you like. Also, I wonder if it's possible to port this as an extension of the "Text" app, b/c that has some nice features, like the directory README's, support in the mobile app, etc. I'd rather not have to disable it, would just like to open markdown files with files_markdown when I'm in the browser.

This is a lovely app, btw, kudos to the devs!

**Comment by jgaehring** [comment]
Oh yea, reading the README for the [Text](https://github.com/nextcloud/text) app it says:

> Nextcloud Text is available for Nextcloud 16 and will be part of Nextcloud 17 as the default text editor.

**Comment by JonisK** [comment]
I can confirm @jgaehring's description. I am also using Nextcloud 19 with the preinstalled *Text* app and *Markdown Editor* would not show up.

How to enable *Markdown Editor* under Nextcloud 19:
1. Disable *Text*
1. Download and enable *Plain text editor*
1. Download and enable *Markdown Editor*

**Comment by zecman** [comment]
Thanks, this save some time of my life. :-)

**Comment by DanScharon** [comment]
In Nextcloud 18 you can have all 3 apps activated, _Text_, _Plain text editor_ and _Markdown Editor_. 
In order to use _Markdown Editor_ instead of _Text_ you then have to open the ... context menu and click "Edit in plain text editor".

**Comment by icewind1991** [comment]
added some instructions to the readme

**Comment by jeffrson** [comment]
Note: Plain text editor *must* be installed for getting this to work. Otherwise there's no context menu item so you can't use files_markdown at all.

Maybe files_markdown should create a context menu item itself? Is this possible?
Is it possible to configure which app opens which file (extensions)?

**Comment by master-fuggi** [comment]
I removed both, the Markdown Editor and the Plain Text Editor again. The shipped Text app has superseded the Markdown Editor. For instance, the shipped Text app even allows for a web view when publicly sharing MD files.
