### ISSUE TITLE
a.katex.renderToString is not a function

### ISSUE THREAD

**Issue by ngoettin** [icewind1991/files_markdown#179]
I installed Nextcloud via [docker](https://hub.docker.com/_/nextcloud/) and wanted to try Collectives as a wiki solution. As I work in a scientific field, math rendering is mandatory and this is why I found your beautiful App.

However, something does not seem to be right; I get the following problem when trying to render a simple equation:
![grafik](https://user-images.githubusercontent.com/56370053/144842727-12e4cccf-be8e-4134-ae00-e7cf3682221a.png)

How can I fix this problem?

**Comment by ryoichikawai** [comment]
I am having the same problem.  When the app was updated to 2.3.5,  the preview window was blank.  I rolled back to the previous version and confirmed that it works correctly.  A few weeks later, I tried 2.3.5 again.  The preview page showed the formatted document but none of equations was rendered.  After each LaTeX expression, ":a.katex.renderToString is not a function" appeared.

KaTeX had a similar issue several years ago (see [https://github.com/KaTeX/KaTeX/issues/937](https://github.com/KaTeX/KaTeX/issues/937)).  

Markdwown Editor: 2.3.5
Nextcloud: 22.2.3

**Comment by TheNeoBurn** [comment]
Same here... Happens even with something simple like `$\color{blue}{TEXT}$` resulting in this:

\color{blue}{TEXT}:a.katex.renderToString is not a function

**Comment by chlarsen** [comment]
This is a regression, as the previous version worked like a charm. And a bit of an emergency, as my TeX-based scientific writing has gone out of the window :-D. Any workaround? Downgrading the app does not work, as the core Nextclouds code insists on the latest app version... Thank you.

**Comment by TheNeoBurn** [comment]
So, I have a dirty work-around. For me, the error occures in ```/apps/files_markdown/build/779.editor.js``` which is a loaded module and does not seem to be part of files_markdown itself. I edited the file, searched for ```a.katex.renderToString``` and changed that to ```a.katex.default.renderToString```, cleared the browser's cache and now it works. It seems to be an issue within the KaTeX module and should be resolved there - but for now this is a quick fix...

**Comment by ryoichikawai** [comment]
Dear, TheNeoBurn.  My sincere gratitude for your remarkably simple solution.  Now my markdown documents are all readable again.
