### ISSUE TITLE
why link on root, cannot made app for virtual instalation on servers

### ISSUE THREAD

**Issue by mckaygerhard** [icewind1991/files_markdown#18]
the document said:

`Clone the app into the /var/www directory:`
`Link the app ownCloud's apps folder as 'files_markdown':`

its possible to just put the app in the app directory and renamed the clone dir to `files_markdown` ?

**Comment by icewind1991** [comment]
Yes

**Comment by mckaygerhard** [comment]
ok, but why the link? there its something that depends on the root web directory or root http request to the server?
