### ISSUE TITLE
Markdown editor doesn't seem to work with .md files at all

### ISSUE THREAD

**Issue by adefaria** [icewind1991/files_markdown#188]
Installed Nextcloud Markdown Editor and enabled it. Went to edit a .md file. Didn't see anything different from the Markdown editor. I believe Nextcloud used the plan text editor instead. Don't see any way to insert a video that is on the Nextcloud server.

**Comment by MilorES** [comment]
Lee la guia tambien tienes que instalar: Edit in plain text editor

**Comment by adefaria** [comment]
I have the plain text editor installed already. I was looking for a way to include a video in md and found Markdown Editor since it said it could do that. After installing it I didn't find a way to include the video.

**Comment by adefaria** [comment]
Long, long have abandoned this. NC is extremely buggy for me so I was gonna use it only as a file store. Now I can't even log in. Sucks.
