### ISSUE TITLE
Request: Open Links in new window / tab

### ISSUE THREAD

**Issue by sydoveton** [icewind1991/files_markdown#19]
Links placed in the document become clickable URL's in the preview. They currently open in the current window. Would prefer an option to make these open in a new window / tab with `_blank`

**Comment by MarcosBL** [comment]
+1

**Comment by IzzySoft** [comment]
Most browsers support that with a middle mouse-click anyway. I'm not aware of any that does not (unless you count MSIE as a browser that is :stuck_out_tongue_winking_eye:)
