### ISSUE TITLE
CHANGELOG.md doesn't contain the latest changes

### ISSUE THREAD

**Issue by Franz-Heinz** [icewind1991/files_markdown#191]
Changes since version 2.3.3 haven't been documented in CHANGELOG.md. Current version is 2.3.6 at the moment.

**Comment by SimJoSt** [comment]
Just stumbled upon the same issue. For context, the 2 relevant URLs:
+ https://github.com/icewind1991/files_markdown/blob/master/CHANGELOG.md
+ https://github.com/icewind1991/files_markdown/releases

Thanks @icewind1991 for the continued work 👍

**Comment by SimJoSt** [comment]
@icewind1991 this is still a thing. To give you a head start for the next time, I prepared an MR for you #211.
