### ISSUE TITLE
[Feature] Copy + Paste of images = automatical upload to OC

### ISSUE THREAD

**Issue by pke** [icewind1991/files_markdown#21]
A feature I like about github & trello is that you can copy+paste images from your localmachine/image URLs when the text area of the editor has the focus and it automatically uploads the file for you (with an automatic name).

Automatic naming would be sub-optimal in the OC case so we could display an input dialog with a pre-populated name for the file (from the filename) and whatever the user enters there will be the name of the file on the owncloud (including relative paths).

What you think?

**Comment by nommaz** [comment]
+1. in face what do you think about using textpack for this? see https://github.com/icewind1991/files_markdown/issues/44

**Comment by icewind1991** [comment]
Fixed with 2.0
