### ISSUE TITLE
No option to view md only, split md/text, text-only

### ISSUE THREAD

**Issue by ralhei** [icewind1991/files_markdown#212]
Hi everybody, this tool really wonderfully parses the markdown code which I'm typing in. But I can't see an option (as indicated in the screenshots from the README) that would allow me to see the plain markdown source code, or even the split view, showing both the source and the rendered markdown. Has this option been removed? 
I'm using Nextcloud Hub 4 (26.0.2) with both  'text' and the 'plain text app' installed and enabled.
I'd be very grateful for any advice.

**Comment by icewind1991** [comment]
You might be editing the file in the "text" app instead of the "plain text app", this app integrates with the "plain text" app, the "text" app has it's own markdown handling

**Comment by ralhei** [comment]
You are completely right, I wasn't even aware that this plain text app existed, because it only shows up when right-clicking on the md-file. Thanks a lot, this really solves my issue.
