### ISSUE TITLE
Feature Request: view full page markup

### ISSUE THREAD

**Issue by wallyreport** [icewind1991/files_markdown#24]
Thanks for creating this. 

I can only view in split page mode. I would be great if I could view the entire page as markdown. Seafile does a decent job of this, if you want to see what I am posting about. 

I would be content to use the regular text editor for editing, and another plugin for viewing the markdown.

**Comment by IzzySoft** [comment]
I second this with a minor deviation: a toggle to switch between edit/edit-with-preview/preview-only would be nice. I'd be contend with the last 2 states :smile_cat:

**Comment by kaksikanaa** [comment]
+1 (huge one) for this!

**Comment by rymdluo** [comment]
+1 for this too. (Btw, if you dock the window to half the screen it's somewhat of a "full page markup") which is what I'm doing.

Unless I can preview with my own css and js files to simulate my own pages, pretty pointless.

**Comment by nommaz** [comment]
agree with @IzzySoft - need to be able to invoke from url as well so we can share link with team members. something like:

- /index.php/apps/files/?fileid=123456#editor
- /index.php/apps/files/?fileid=123456#viewer
- /index.php/apps/files/?fileid=123456#dual

**Comment by IzzySoft** [comment]
@nommaz minor correction to that: Using anchors for the viewing mode might collide with anchors defined in the document. So if you want to pass that along, rather use something like `/index.php/apps/files/?fileid=123456&mode=editor` – which then also would allow something like `/index.php/apps/files/?fileid=123456&mode=viewer#editor` to jump to the anchor `<div id='editor'>` in viewer mode ;)
