### ISSUE TITLE
Links to anchors within the document

### ISSUE THREAD

**Issue by IzzySoft** [icewind1991/files_markdown#26]
When creating headers (e.g. `## My Header`), the rendered view creates an HTML header with ID (with the example: `<h2 id="md-my-header">`. Unfortunately, if one uses that in a link within the document (`see [My Header](#md-my-header))`, it cannot be clicked – or rather when clicked, one ends up in the file list again.

Can anything be done to instead jump to the anchor within the preview? This would be especially useful for slightly larger documents (also think of a TOC, see #22 ) and in connection with #24.

While on this topic: which other Markdown processors would use the same mechanism to create the ID? To my knowledge, there are at least 2 different approaches:

* Markdown Extra uses attributes to create IDs/classes (above example would become `## My Header { #my-header }` with that)
* Github flavored Markdown would skip the `md-` prefix, spaces-to-minus, and forced-lowercase (`id="MyHeader"`)

So it might even be considered to change the anchor generation in this context to e.g. support Markdown Extra and fall back to Github-Flavor when no attribute is given.

**Comment by icewind1991** [comment]
Fixed with 2.0

Write your links like `[link](#My-Header]` (markdown doesn't allow for spaces in links)
