### ISSUE TITLE
Can't install from app store

### ISSUE THREAD

**Issue by schiessle** [icewind1991/files_markdown#30]
I just saw that you uploaded the app to the app store. So I removed my git checkout and tried to install it instead from the app store. The app gets downloaded by then I get this error:

````Error: this app cannot be enabled because it makes the server unstable````

Any idea why?

**Comment by schiessle** [comment]
When I try to enable it a second time it works. But still a strange error. I saw this the first time with the Markdown app all other apps I installed don't show this behavior.

**Comment by icewind1991** [comment]
Anything in the log?

**Comment by schiessle** [comment]
no, nothing in the log. I also tried to reproduce it on my development environment but couldn't reproduce. Maybe any side effect because I had it installed from git before?
