### ISSUE TITLE
Enable Spell checking

### ISSUE THREAD

**Issue by Bladou46** [icewind1991/files_markdown#31]
Hello, 

It would be great if possible to add spell checker or allow external plugins to work with this editor. 
I tested on Chrome and Firefox. In both cases, this is not working with the browser's integrated spell checking.

**Comment by icewind1991** [comment]
Spellchecker support should be added as part of the text editor itself, this app only adds the markdown preview support.

Feel free to reopen this issue at the [texteditor issue tracker](https://github.com/nextcloud/files_texteditor)
