### ISSUE TITLE
NC 11: Preview not available

### ISSUE THREAD

**Issue by Huster-at-github** [icewind1991/files_markdown#32]
# Bug report
## Expected Behavior
![embed](https://cloud.githubusercontent.com/assets/3857906/21524438/5ce32de4-cd16-11e6-934b-fa147cf5b62d.png)
![preview](https://cloud.githubusercontent.com/assets/3857906/21524439/5ce39e8c-cd16-11e6-8455-ed3e2abfa2fb.png)

## Current Behavior
![bildschirmfoto vom 2016-12-28 15-53-13](https://cloud.githubusercontent.com/assets/3857906/21524454/74cdeff2-cd16-11e6-9d87-05c623484a3c.png)
![bildschirmfoto vom 2016-12-28 15-54-17](https://cloud.githubusercontent.com/assets/3857906/21524453/74cd9f98-cd16-11e6-80c4-397670651737.png)

## Your Environment
* Markdown Editor 1.0.0
* Text editor 2.2
* Browser Name and version: Firefox 50.1.0
* Operating System and version (desktop or mobile): Ubuntu 16.04
* Nextcloud version: 11.0.0
* PHP version: PHP 7.0.8-0ubuntu0.16.04.3
* Database version: mysql  Ver 14.14 Distrib 5.7.16
* Are you using encryption: no

## Log File Content
Info	admin_audit	File accessed: "/clientsync/Config/Markdown-Test.md"	2016-12-28T15:34:47+0100
Info	admin_audit	File accessed: "/clientsync/Config/Markdown-Test.md"	2016-12-28T15:34:38+0100
Info	admin_audit	File renamed: "/clientsync/Config/Markdown-Test.txt" to "/clientsync/Config/Markdown-Test.md"	2016-12-28T15:34:29+0100
Info	admin_audit	File accessed: "/clientsync/Config/Markdown-Test.txt"	2016-12-28T15:34:21+0100
Info	admin_audit	File accessed: "/clientsync/Config/Markdown-Test.txt"	2016-12-28T15:33:53+0100
Debug	core	OC_Image->loadFromBase64, could not load	2016-12-28T15:33:43+0100
Info	admin_audit	File accessed: "/clientsync/Config/Markdown-Test.txt"	2016-12-28T15:33:43+0100
Info	admin_audit	File accessed: "/clientsync/Config/Markdown-Test.txt"	2016-12-28T15:33:43+0100
Info	admin_audit	File accessed: "/clientsync/Config/Markdown-Test.txt"	2016-12-28T15:33:41+0100
Info	admin_audit	File accessed: "/clientsync/Config/Markdown-Test.txt"	2016-12-28T15:33:35+0100
Info	admin_audit	File written to: "/clientsync/Config/Markdown-Test.txt"	2016-12-28T15:33:29+0100
Info	admin_audit	File updated: "/clientsync/Config/Markdown-Test.txt"	2016-12-28T15:33:29+0100
Info	admin_audit	File accessed: "/clientsync/Config/Markdown-Test.txt"	2016-12-28T15:33:21+0100
Info	admin_audit	File accessed: "/clientsync/Config/Markdown-Test.txt"	2016-12-28T15:33:21+0100
Debug	core	OC_Image->loadFromBase64, could not load	2016-12-28T15:33:19+0100
Info	admin_audit	File accessed: "/clientsync/Config/Markdown-Test.txt"	2016-12-28T15:33:18+0100
Info	admin_audit	File accessed: "/clientsync/Config/Markdown-Test.txt"	2016-12-28T15:33:18+0100
Info	admin_audit	File written to: "/clientsync/Config/Markdown-Test.txt"	2016-12-28T15:33:15+0100
Info	admin_audit	File updated: "/clientsync/Config/Markdown-Test.txt"	2016-12-28T15:33:15+0100
Info	admin_audit	File accessed: "/clientsync/Config/Markdown-Test.txt"	2016-12-28T15:33:10+0100
Info	admin_audit	File accessed: "/clientsync/Config/Markdown-Test.txt"	2016-12-28T15:32:31+0100
Info	admin_audit	File accessed: "/clientsync/Config/Markdown-Test.txt"	2016-12-28T15:30:33+0100
Info	admin_audit	File accessed: "/clientsync/Config/Markdown-Test.txt"	2016-12-28T15:30:21+0100
Info	admin_audit	File accessed: "/clientsync/Config/Markdown-Test.txt"	2016-12-28T15:30:19+0100
Debug	cron	Finished OC\Command\CommandJob job with ID 340	2016-12-28T15:30:18+0100
Info	files_versions	Expire: /clientsync/Config/Markdown-Test.txt.v1482934762	2016-12-28T15:30:18+0100
Info	admin_audit	Version "/clientsync/Config/Markdown-Test.txt.v1482934762" was deleted.	2016-12-28T15:30:18+0100
Info	files_versions	Mark to expire /clientsync/Config/Markdown-Test.txt next version should be 1482934707 or smaller. (prevTimestamp: 1482934767; step: 60	2016-12-28T15:30:18+0100

**Comment by icewind1991** [comment]
Are you sure the app is enabled?

Is there anything in the browser log when you try to open a md file

**Comment by Huster-at-github** [comment]
Cannot reproduce this.

Sorry, I'll close this ticket.
