### ISSUE TITLE
Numbered list display

### ISSUE THREAD

**Issue by baloan** [icewind1991/files_markdown#35]
Markdown fails to render orphan last list elements:
![image](https://cloud.githubusercontent.com/assets/651799/22076119/0950b558-ddaf-11e6-95e9-e3118843028c.png)
Works fine with Markdownpad2:
![image](https://cloud.githubusercontent.com/assets/651799/22076137/1bf68034-ddaf-11e6-8566-92c0a4b383bf.png)

**Comment by icewind1991** [comment]
Fix released with 1.0.1
