### ISSUE TITLE
Save only after some more time / the file is closed

### ISSUE THREAD

**Issue by MariusBluem** [icewind1991/files_markdown#36]
<img width="378" alt="bildschirmfoto 2017-01-28 um 16 16 13" src="https://cloud.githubusercontent.com/assets/19711361/22397599/3f793862-e575-11e6-906a-7acbd9941e8e.png">
...my markdown is saved after every word 😅

**Comment by icewind1991** [comment]
This is an issue with the [texteditor](https://github.com/nextcloud/files_texteditor), this app only provides the markdown preview.

Please open an issue there
