### ISSUE TITLE
Can not use it when I also want to use the mail app

### ISSUE THREAD

**Issue by stevleibelt** [icewind1991/files_markdown#37]
Hey, I've no idea why this happens but the bad thing is that I have to decide which app I want to run.
Either this cool app or the mail app.
If I install this app, the mail app [is not loading](https://github.com/nextcloud/mail/issues/275) and this can only be fixed by [disabling your app](https://github.com/nextcloud/mail/issues/234#issuecomment-266735169).
This is sad and my gut feeling is, that it could be a simple configuration setting.

**Comment by Berndinox** [comment]
Same here!

**Comment by icewind1991** [comment]
Fix released with 1.0.1
