### ISSUE TITLE
Feature Request: Synchronized scrolling between editor and preview

### ISSUE THREAD

**Issue by superjamie** [icewind1991/files_markdown#4]
It's pretty common for Markdown editors to synchronise the scrolling of the editor with the scrolling of the preview, or vice versa.

Put a long file into [dillinger.io](http://dillinger.io/) for a working demonstration.

It would be neat to have this in owncloud-markdown as well.

**Comment by metal3d** [comment]
:+1: 
That's what I saw on stackedit.io too. That could be great.

**Comment by ennnnno** [comment]
yes, that would be nice :+1:

**Comment by sydoveton** [comment]
+1 for me

**Comment by luckydonald** [comment]
The page linked above doesn't do a good job, they are just both scrolling, no content awareness.

**Comment by icewind1991** [comment]
Fixed with 2.0
