### ISSUE TITLE
About Chinese issue

### ISSUE THREAD

**Issue by xujwoo** [icewind1991/files_markdown#48]
When I use the input method to enter the Chinese language will appear when the problem of dislocation, and hit the space bar can not be selected to enter the Chinese.

**Comment by Acris** [comment]
+1

**Comment by Acris** [comment]
See: https://github.com/nextcloud/notes/issues/59#issuecomment-312204569

**Comment by icewind1991** [comment]
This is a duplicate of https://github.com/nextcloud/files_texteditor/issues/44, this app only provides the md preview
