### ISSUE TITLE
Embedded images will not be shown

### ISSUE THREAD

**Issue by artemanufrij** [icewind1991/files_markdown#49]
md line: `![](arch_logo.png)`
 
app try to load following url: `/index.php/remote.php/files//Notizen/arch_logo.png`

`/index.php` should be removed from generated url...

PS: I'm using NC12

**Comment by artemanufrij** [comment]
if you replace `index.php` it works:
`return OC.generateUrl('remote.php/files/' + path).replace('/index.php', '');` 
I know it's not the clearest way :)

**Comment by icewind1991** [comment]
Should be fixed with https://github.com/icewind1991/files_markdown/commit/6891c3635d2de0899938e2176611da47716a3589
