### ISSUE TITLE
Make the preview view collapsible / hideable

### ISSUE THREAD

**Issue by mpathy** [icewind1991/files_markdown#51]
Sometimes, one will just want to edit his markdown files, without the need to see them all the time and needs the space to edit.

So it would be great if its possible to hide the preview view to the side..

**Comment by icewind1991** [comment]
This is already possible with recent versions of the texteditor

![screenshot_20170628_131655](https://user-images.githubusercontent.com/1283854/27634607-2ad0d18a-5c04-11e7-8ab9-48bf1daf8264.png)
