### ISSUE TITLE
not Working

### ISSUE THREAD

**Issue by olissongs** [icewind1991/files_markdown#52]
Hi,
i installed this app in Nexxtcloud 12.0.0, enabling it, nothing happens.
Any Ideas?

**Comment by icewind1991** [comment]
If you want help you'll have to provide more information that this.

How are you trying to use it, what do you see when you try to use it (expected vs actual behaviour) are the any relevant errors in the browser or nextcloud logs.

**Comment by olissongs** [comment]
Hi, sorry i've got it.
it was an misunderstanding in how the thing works.
the editor is only shown in files with extension .md
may thats worth for an tipp in the readme file?
