### ISSUE TITLE
Photos inside text are not shown anymore in the preview

### ISSUE THREAD

**Issue by Franktdf** [icewind1991/files_markdown#55]
Hello,

Photos, which are linked into the test like (example pic from editor.md):

` ![](https://pandao.github.io/editor.md/examples/images/4.jpg) `

I think it worked some time before, so I assume it is a bug.
I tried on 2 different servers, one on my nextcloud running on dietpi and the other in the internet on a website hosting provider.

Would be nice if that could be fixed.

Greetings,
Frank

**Comment by icewind1991** [comment]
Fixed with d4ce7b0d27dd53d0538db21f3c59d7b989371fc6
