### ISSUE TITLE
markdown in chrome on android

### ISSUE THREAD

**Issue by andrewmcguinness** [icewind1991/files_markdown#56]
I can't see the rendered markdown in chrome for android on a phone. It does work if you check "Request desktop site" on the browser, but that's rather awkward.

In side-by-side mode, I just see the source. In preview mode, I get a blank page. It makes sense that side-by-side wouldn't work on a phone, but preview ought to work, and would be hugely useful for me.

**Comment by icewind1991** [comment]
Fixed with https://github.com/nextcloud/files_texteditor/pull/61

**Comment by andrewmcguinness** [comment]
Confirmed working (now I'm finally on nextcloud 13). Thanks!
