### ISSUE TITLE
because it violates the following Content Security Policy

### ISSUE THREAD

**Issue by isafe** [icewind1991/files_markdown#58]
<img width="1344" alt="screen shot 2017-09-07 at 2 53 39 pm" src="https://user-images.githubusercontent.com/5019002/30150010-7008891c-936f-11e7-9206-677b6ea70408.png">

**Comment by icewind1991** [comment]
Can you post the output of `$('script[nonce]')[0].getAttribute('nonce')` and compare that with the nonce from the csp error.

**Comment by varakh** [comment]
Same error here. This prevents a preview.

`$('script[nonce]')[0].getAttribute('nonce')` output is `""`.

**Comment by icewind1991** [comment]
Weird, what is `$('script[nonce]')[0]`?

**Comment by varakh** [comment]
`$('script[nonce]')[0]
<script nonce type=​"text/​javascript">​				var oc_debug=false;
var oc_isadmin=false;
var oc_dataURL=false;
var oc_webroot="";
.......`

**Comment by icewind1991** [comment]
Hmm, ok.

Can you try `$('script[nonce][src]')[0].getAttribute('nonce')`

**Comment by varakh** [comment]
Result is `""`

**Comment by icewind1991** [comment]
@varakh one more attempt `$('script[nonce]:not([nonce=""])').attr('nonce')`

**Comment by varakh** [comment]
Result it `undefined`

**Comment by icewind1991** [comment]
Ok, I have no idea what's going on here.

what browser are you using?
can you try disabling the browser plugins?
can you check the page source and check if any `<script>` tags have a nonce set

**Comment by guzzard** [comment]
Hi @icewind1991,

Chromium 61.0.3163.79 - Not working, with/without plugins doesn't matter
Firefox 55.0.3 - Works

Chromium stops the script from loading since it breaks the Content Security Policy.

I think solution might be found here?
https://developer.chrome.com/extensions/contentSecurityPolicy#relaxing

Related:
https://bugs.chromium.org/p/chromium/issues/detail?id=107538

**Comment by icewind1991** [comment]
The *problem* is that it works perfectly fine for me on chromium 61.

The csp issues are caused by the script not being able to detect the current nonce to correctly load additional scripts

**Comment by pietrodn** [comment]
Same issue in Google Chrome 61.0.3163.79 on macOS 10.12.

**Comment by icewind1991** [comment]
Can you check the result of `document.querySelector('[nonce]').nonce`

**Comment by guzzard** [comment]
Chromium:
document.querySelector('[nonce]').nonce;
"cFVIR045SDArbnd1TmxVTVJvUmE2RHMxVkVlM0ZCZ1k0aFlOUE92Qk1kdz06N0RHcldxU210eE40RGlaWUZmTUwyMnRBSmd2bVFGMUNzWGdtY29EekNPaz0="

Firefox:
document.querySelector('[nonce]').nonce;
undefined

**Comment by icewind1991** [comment]
Ok, that method not working on FF is known to me.

I will release an update which should solve the problem tomorrow

**Comment by icewind1991** [comment]
This should be fixed with 2.0.1

**Comment by pietrodn** [comment]
I confirm that 2.0.1 fixes this for me. Thank you!

**Comment by guzzard** [comment]
working great now, thanks :+1:
