### ISSUE TITLE
Cannot edit markdown files in remote storage

### ISSUE THREAD

**Issue by quentinus95** [icewind1991/files_markdown#65]
I can't manage to edit markdown files located in a remote location (mounted using WebDav).

When the `.md` file is not in the remote folder, I can edit it:

![image](https://user-images.githubusercontent.com/8060564/30423553-78e6648a-9943-11e7-8e7b-48af1692194a.png)

When the `.md` file is moved to the remote folder, the file is not recognized any more:

![image](https://user-images.githubusercontent.com/8060564/30423658-d5de1408-9943-11e7-87f8-cc7ba12ea01b.png)

**Comment by mr-bolle** [comment]
Hi, i try to edit a markdown file with a Windows 7 webdav hare. 
And if i edit this file local, i can see this changes into the Nextcloud Session.

I also try to share a file from Server 1 to the Server 2. And if i use the webdav share from Server 2, i can also edit the markdown file. And see the changes into markdown editor app.

![26-09-_2017_20-13-50](https://user-images.githubusercontent.com/22414212/30876875-34ee8ad2-a2f8-11e7-9689-143afe14a05b.png)

**Comment by quentinus95** [comment]
Can you confirm that you can edit the file using the online editor when dropping the file on a remote folder only using the web interface (on a folder mounted using [External storage support](https://docs.nextcloud.com/server/9/admin_manual/configuration_files/external_storage_configuration_gui.html)) ?

**Comment by mr-bolle** [comment]
Now i test to share a webdav folder with the external storage. I can edit this file however, i have see that when saving the message appears 'File is locked'

This error occurs also with the integrated editor, therefore I would guess that a bug in the external storage support, or some other issue with the permission.

![](https://user-images.githubusercontent.com/22414212/30923719-ee65b666-a3ac-11e7-9766-e5876cfcb1dc.png)

**Comment by quentinus95** [comment]
This is strange, because if I remember well, I wasn't able to reproduce the issue with the text editor, only with markdown editor which would suggest an bug in the later one.

Maybe this can be linked to an issue for recognizing the supported files?

Which version of NextCloud are you using?

**Comment by mr-bolle** [comment]
I use version 12.0.3 and can also reproduce the error with new created files. And see this problem also into the logging

**Comment by quentinus95** [comment]
Strange that you cannot create a file. Are you sure that the folder is not read only?

**Comment by mr-bolle** [comment]
Yes i have write access, i try to move some files into the share - and this works

I connect to box.com webdav account, and see the same behavor. [youtube Video](https://youtu.be/StFlmKO1L3Y)

**Comment by MorrisJobke** [comment]
@icewind1991 Fixed in server
