### ISSUE TITLE
[feature suggest] Enable editor on share mode

### ISSUE THREAD

**Issue by thesteff** [icewind1991/files_markdown#73]
Hi !

Your wisiwig markdown editor is really great. I suggest made it working when we share a .md file by link (in view mode like with "pico cms" but with just a generated link OR allowing view and edit mode) . This functionality could permit a group to easily work together on a file without creating log profils for each users.

Great work by the way !

**Comment by TigerDK** [comment]
Second this. I use the share feature a lot and have started to use markdown editor. Right now people either have to live with the source code or I should convert it to a png/pdf or the like prior to sharing.

**Comment by icewind1991** [comment]
This would have to be implemented in https://github.com/nextcloud/files_texteditor since this app only provides the preview plugin for that app. Feel free to open an issue for this over there
