### ISSUE TITLE
Make replacing spaces with tabs optional

### ISSUE THREAD

**Issue by arnowelzel** [icewind1991/files_markdown#76]
When entering multiple spaces, the editor replaces them with tabs assuming tab stops every 4 spaces. This can cause confusion when opening the file somewhere else where the tab stops are 8 spaces and also when editing tables which are created to be readable even without a markdown formatter.

It would be nice, if this behaviour could be disabled with a setting.

**Comment by icewind1991** [comment]
This behaviour is part of the texteditor and not the markdown preview, please re-open this issue in the nextcloud text editor repo
