### ISSUE TITLE
Problem with Markdown Editor on Nextcloud app store?

### ISSUE THREAD

**Issue by wisdomlight** [icewind1991/files_markdown#77]
In the Nextcloud app store  the Office & Text category
Whereas all the other apps have an image [what they look like]
The Markdown editor has a on going circle instead of an image

I enable the markdown but I am not sure anything actually happens.

How do i know if the markdown works or not 

cheers

**Comment by habernal** [comment]
I can confirm the mentioned bug: There is no official screenshot shown in the Nextcloud App Store. However, after enabling (installing) the plugin, it works nicely. (hint for @wisdomlight : just try to edit any .md file). Tested on Nextcloud 13.0.

**Comment by wisdomlight** [comment]
@habernal 
Thanks!
it does indeed work.
I did not understand that i needed to .md the file
cheers
