### ISSUE TITLE
no line-wrap in combined viewing mode

### ISSUE THREAD

**Issue by ebiel** [icewind1991/files_markdown#78]
When the viewing mode is the combined one (source on the left side, formatted output on the right) there is no line wrap on the left side and no scroll bar at the bottom.
Therefore, when the line is getting longer than the viewable area there is no way to see the actual content.
![long line](https://user-images.githubusercontent.com/5073283/36205750-1296d9d8-1190-11e8-9f0a-dc7e5178392c.png)

**Comment by Isvvc** [comment]
It has to do with the open animation. The initial window is visually wider than the post-animation one, but the text field is the same size. There is text wrapping, but it just goes a bit off under the preview half.

A temporary fix is to, once the file is open and the animation complete, zoom in or out the page on your browser then reset the zoom. This will make it wrap properly.

**Comment by icewind1991** [comment]
This should be fixed now with #96, feel free to reopen if this is still an issue

**Comment by porjo** [comment]
I've just hit this issue using Nextcloud 15.0.5. It's not clear to me if the referenced fix should be in that version or not?
