### ISSUE TITLE
Ctrl+l keyboard shortcut overrides a default behavior of common browsers

### ISSUE THREAD

**Issue by ebiel** [icewind1991/files_markdown#79]
There is Ctrl+l keyboard shortcut that opens up an input box where you may enter a line number to directly jump to.

However, the same keyboard shortcut is used by some/most browsers (Firefox, Chrome), to enter the URL or input field that allows to navigate to a website. This is not possible anymore when the editor is open.

Suggestion: Use another keyboard shortcut to go to a particular line.

**Comment by icewind1991** [comment]
Please open an issue in the files_texteditor repo, this app only provides the markdown preview
