### ISSUE TITLE
README examples do not work

### ISSUE THREAD

**Issue by gorn** [icewind1991/files_markdown#84]
Examples from [README.md](../blob/master/README.md) do not work. For esample

 ```
![](nextcloud.jpg)
```

 does not render how it is shown and even the "absolute path" example

 ```
 ![](logo.png)
```
 two lines after that neither works, not makes any sense, as it is not absolute path. Currently it is very difficult to use relative links. It should be handeled the same way as [relative links in github](https://help.github.com/articles/basic-writing-and-formatting-syntax/#relative-links) as mentioned in #41

**Comment by icewind1991** [comment]
The second part is a mistake in the screenshot and has now been corrected.

Are you sure you have the images in the correct path that you're trying to embed

**Comment by gorn** [comment]
I have standard installation of nextcloud - does the readme need to manually add some images somewhere before it works? If so than it should be mentioned.

**Comment by gorn** [comment]
How this was resolved? In which version?
