### ISSUE TITLE
Lines of text hidden behind preview in mixed mode

### ISSUE THREAD

**Issue by SimJoSt** [icewind1991/files_markdown#95]
When using mixed mode, I would expect the lines of the raw editor to end where it meets the preview.
But the lines extend to the full length as if they were in editor-only mode. The preview overlays half of the line.
At least a scrollbar at the bottom of the editor should be added.

**Comment by Isvvc** [comment]
Zooming the page in or out, then resetting the zoom in your browser each time you open a file for editing works as a temporary fix until it gets sorted out.

**Comment by icewind1991** [comment]
Please test if applying https://github.com/nextcloud/files_texteditor/pull/96 to the texteditor fixes the problem for you

**Comment by SimJoSt** [comment]
@icewind1991 Finally got around to testing it.
Works like a charm now.
Looking forward to having it fixed by default in Nextcloud 14 :-)
